name: update_devOps_check

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  notification:
    if: always()
    uses: ./.github/workflows/Reusable Notification.yml
    secrets: inherit
    with:
      message: |
        Dev Ops ทำงานหน่อยว้อยยย..!!!
        Actor: ${{ github.event.head_commit.author}}
        Message: ${{ github.event.head_commit.message }}
        Status: ${{ needs.deploy.result }}
        Repository: ${{ github.repository }}
        Branch: ${{ github.ref_name }}
